# Generated by Django 2.2.11 on 2021-01-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(default='', max_length=20)),
                ('image_1', models.CharField(blank=True, default='', max_length=2000000, null=True)),
                ('image_2', models.CharField(blank=True, default='', max_length=2000000, null=True)),
                ('image_3', models.CharField(blank=True, default='', max_length=2000000, null=True)),
                ('image_4', models.CharField(blank=True, default='', max_length=2000000, null=True)),
                ('image_5', models.CharField(blank=True, default='', max_length=2000000, null=True)),
            ],
        ),
    ]
