# Generated by Django 2.2.11 on 2020-09-07 07:56

import FirstApp.MongoModels
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=None)),
                ('lecture_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_id', models.CharField(max_length=7)),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('seconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fps', models.IntegerField()),
                ('frame_count', models.IntegerField()),
                ('happy_count', models.IntegerField()),
                ('sad_count', models.IntegerField()),
                ('angry_count', models.IntegerField()),
                ('neutral_count', models.IntegerField()),
                ('surprise_count', models.IntegerField()),
                ('happy_perct', models.IntegerField()),
                ('sad_perct', models.IntegerField()),
                ('angry_perct', models.IntegerField()),
                ('neutral_perct', models.IntegerField()),
                ('surprise_perct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.TextField()),
                ('name', models.TextField()),
                ('year', models.IntegerField()),
                ('faculty', models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_video_id', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('video_name', models.CharField(max_length=50)),
                ('video_length', models.DurationField()),
                ('lecturer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Lecturer')),
                ('subject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_subject_id', models.CharField(max_length=10)),
                ('lecturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Lecturer')),
                ('subjects', models.ManyToManyField(to='FirstApp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=15)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='LecturePoseEstimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_pose_id', models.CharField(max_length=10)),
                ('lecture_video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureVideo')),
            ],
        ),
        migrations.CreateModel(
            name='LectureEmotionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_emotion_id', models.CharField(max_length=10)),
                ('happy_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('sad_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('angry_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('disgust_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('surprise_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('neutral_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('lecture_video_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureVideo')),
            ],
        ),
        migrations.CreateModel(
            name='LectureActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_activity_id', models.CharField(max_length=10)),
                ('talking_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('listening_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('writing_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('phone_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('lecture_video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureVideo')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_id', models.CharField(max_length=10)),
                ('timetable', djongo.models.fields.ArrayField(model_container=FirstApp.MongoModels.DateTimeTable)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Faculty')),
            ],
        ),
    ]
