# Generated by Django 2.2.11 on 2020-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_registeruser_video_videometa'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureEmotionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=10)),
                ('happy_perct', models.FloatField()),
                ('sad_perct', models.FloatField()),
                ('angry_perct', models.FloatField()),
                ('surprise_perct', models.FloatField()),
                ('disgust_perct', models.FloatField()),
                ('neutral_perct', models.FloatField()),
            ],
        ),
    ]
