# Generated by Django 2.2.11 on 2020-08-25 11:28

import FirstApp.MongoModels
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_lecturercredentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectureemotionreport',
            old_name='lecture_id',
            new_name='lecture_emotion_id',
        ),
        migrations.AlterField(
            model_name='lectureemotionreport',
            name='angry_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='lectureemotionreport',
            name='disgust_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='lectureemotionreport',
            name='happy_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='lectureemotionreport',
            name='neutral_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='lectureemotionreport',
            name='sad_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='lectureemotionreport',
            name='surprise_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_video_id', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('video_name', models.CharField(max_length=50)),
                ('video_length', models.DurationField()),
                ('lecturer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Lecturer')),
                ('subject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='LectureGazeEstimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_gaze_id', models.CharField(max_length=10)),
                ('lecture_video_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureVideo')),
            ],
        ),
        migrations.CreateModel(
            name='LectureActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_activity_id', models.CharField(max_length=10)),
                ('talking_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('listening_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('writing_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('phone_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('lecture_video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureVideo')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_id', models.CharField(max_length=10)),
                ('timetable', djongo.models.fields.ArrayField(model_container=FirstApp.MongoModels.DateTimeTable)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='lectureemotionreport',
            name='lecture_video_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureVideo'),
        ),
    ]
