# Generated by Django 2.2.11 on 2020-08-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0007_auto_20200825_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturegazeestimation',
            name='looking_down_and_left_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='lecturegazeestimation',
            name='looking_down_and_right_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='lecturegazeestimation',
            name='looking_front_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='lecturegazeestimation',
            name='looking_up_and_left_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='lecturegazeestimation',
            name='looking_up_and_right_perct',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
