# Generated by Django 2.2.11 on 2020-10-07 12:29

import FirstApp.MongoModels
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0008_auto_20200825_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureActivityFrameGroupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_group', models.CharField(max_length=10)),
                ('phone_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('listening_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('writing_perct', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='LectureActivityFrameGroupings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('frame_group_details', djongo.models.fields.ArrayField(model_container=FirstApp.MongoModels.LectureActivityFrameGroupDetails)),
                ('lecture_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureActivity')),
            ],
        ),
    ]
