# Generated by Django 2.2.11 on 2020-10-08 17:02

import FirstApp.MongoModels
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0008_auto_20200825_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureActivityFrameGroupings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_activity_frame_groupings_id', models.CharField(default='', max_length=15)),
                ('frame_group_details', djongo.models.fields.ArrayField(model_container=FirstApp.MongoModels.LectureActivityFrameGroupDetails)),
                ('lecture_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureActivity')),
            ],
        ),
    ]
