# Generated by Django 2.2.11 on 2020-10-09 16:58

import FirstApp.MongoModels
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0010_lecturevideoframelandmarks_lecturevideotimelandmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureGazeFrameGroupings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_gaze_frame_groupings_id', models.CharField(default='', max_length=15)),
                ('frame_group_details', djongo.models.fields.ArrayField(model_container=FirstApp.MongoModels.LectureGazeFrameGroupDetails)),
                ('lecture_gaze_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureGazeEstimation')),
            ],
        ),
        migrations.CreateModel(
            name='LectureEmotionFrameGroupings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_emotion_frame_groupings_id', models.CharField(default='', max_length=15)),
                ('frame_group_details', djongo.models.fields.ArrayField(model_container=FirstApp.MongoModels.LectureEmotionFrameGroupDetails)),
                ('lecture_emotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureEmotionReport')),
            ],
        ),
    ]
