# Generated by Django 2.2.11 on 2020-10-16 17:07

import FirstApp.MongoModels
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0011_lectureemotionframegroupings_lecturegazeframegroupings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureActivityFrameRecognitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_activity_frame_recognition_id', models.CharField(max_length=15)),
                ('frame_recognition_details', djongo.models.fields.ArrayField(model_container=FirstApp.MongoModels.LectureActivityFrameRecognitionDetails)),
                ('lecture_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureActivity')),
            ],
        ),
    ]
