# Generated by Django 2.2.11 on 2020-10-17 14:01

import FirstApp.MongoModels
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0012_lectureactivityframerecognitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureEmotionFrameRecognitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_emotion_frame_recognition_id', models.CharField(max_length=15)),
                ('frame_recognition_details', djongo.models.fields.ArrayField(model_container=FirstApp.MongoModels.LectureEmotionFrameRecognitionDetails)),
                ('lecture_emotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.LectureEmotionReport')),
            ],
        ),
    ]
