# Generated by Django 2.2.11 on 2020-09-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_audio_id', models.CharField(max_length=10)),
                ('lecturer_date', models.DateField()),
                ('lecture_audio_name', models.CharField(max_length=50)),
                ('lecture_audio_length', models.DurationField()),
                ('lecturer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Lecturer')),
                ('subject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='LectureAudioSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_audio_summary_id', models.CharField(max_length=10)),
                ('audio_original_text', models.TextField()),
                ('audio_summary', models.TextField()),
                ('lecture_audio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LectureSummarizingApp.LectureAudio')),
            ],
        ),
    ]
