# Generated by Django 2.2.12 on 2020-09-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LectureSummarizingApp', '0002_lectureaudionoiseremoved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectureaudionoiseremoved',
            old_name='lecture_audio_id',
            new_name='lecture_audio_noise_removed_id',
        ),
    ]
