# Generated by Django 2.2.11 on 2020-09-15 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FirstApp', '0001_initial'),
        ('LectureSummarizingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('seconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LecturerVideoMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fps', models.IntegerField()),
                ('frame_count', models.IntegerField()),
                ('seated_count', models.IntegerField()),
                ('standing_count', models.IntegerField()),
                ('walking_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=15)),
                ('lName', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LectureRecordedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_video_id', models.CharField(max_length=10)),
                ('lecturer_date', models.DateField()),
                ('lecture_video_name', models.CharField(max_length=50)),
                ('lecture_video_length', models.DurationField()),
                ('lecturer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Lecturer')),
                ('subject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FirstApp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerAudioText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_audio_text_id', models.CharField(max_length=10)),
                ('lecturer_audio_text_wordcount', models.IntegerField()),
                ('lecturer_audio_text_lexical_wordcount', models.IntegerField()),
                ('lecturer_audio_text_non_lexical_wordcount', models.IntegerField()),
                ('lecturer_audio_original_text', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LectureSummarizingApp.LectureAudioSummary')),
            ],
        ),
    ]
