# Generated by Django 2.2.11 on 2020-09-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorLecturerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureraudiotext',
            name='lecturer_audio_text_status',
            field=models.CharField(choices=[(1, 'Below'), (2, 'Average'), (3, 'Excellent')], default='Average', max_length=15),
        ),
    ]
