# Generated by Django 2.2.11 on 2020-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorLecturerApp', '0002_lectureraudiotext_lecturer_audio_text_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureraudiotext',
            name='lecturer_audio_text_status',
            field=models.CharField(choices=[('Below', 'Below'), ('Average', 'Average'), ('Excellent', 'Excellent')], default='Average', max_length=15),
        ),
    ]
