# Generated by Django 2.2.11 on 2020-09-30 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorLecturerApp', '0003_auto_20200915_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturervideometadata',
            name='lecturer_video_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MonitorLecturerApp.LectureRecordedVideo'),
        ),
    ]
